### PR TITLE
Allow hostnames in GSB_URL

### PR DESCRIPTION
**Pull request by Wiezzel**
Because why not?

### CODE REVIEW

**Review by tworec — APPROVED** [review]

**Review by mfranciszkiewicz — DISMISSED** [review]

**Comment by Wiezzel** [comment]
@tworec @mfranciszkiewicz 
It has been pointed out to me by @prekucki that this PR uses synchronous DNS resolution that will slow down yagna startup. A better alternative would be to resolve the hostname asynchronously on connection but it requires more effort to implement and I probably won't be able to do this now as part of this PR. Would like me to close it or merge anyway?

**Comment by mfranciszkiewicz** [comment]
@Wiezzel I think it's better to refactor this PR and merge it later

**Review by tworec — CHANGES_REQUESTED** [review]
pls refactor as you've proposed

**Comment by Wiezzel** [comment]
@tworec @mfranciszkiewicz Async DNS resultion ready.

**Review by mfranciszkiewicz — APPROVED** [review]

**Review by tworec — APPROVED** [review]

**Comment by Wiezzel** [comment]
@mfranciszkiewicz Plz, merge. I'm not authorized.

**Comment by tworec** [comment]
Let's merge it after Beta.2 to be included in [beta.2.patch.1](https://github.com/golemfactory/ya-service-bus/labels/beta.2.patch.1)

**Pull request merged**
